### ISSUE TITLE
Allow None as a value for get_keys

### ISSUE THREAD

**Issue by tiltingpenguin** [tiltingpenguin/python-libeconf#5]
There currently exists a bug where `get_keys()` fails when no group is provided. According to the libeconf documentation, not providing a group should lead to all keys being returned, but we get a NOKEY Error instead

**Comment by aplanas** [comment]
Did you create an issue in libeconf?

**Comment by tiltingpenguin** [comment]
My impression was that this bug comes from the python side, but I haven't confirmed this yet

**Comment by tiltingpenguin** [comment]
Opened https://github.com/openSUSE/libeconf/issues/187 regarding this issue
